### ISSUE TITLE
mobile端更改登录密码获取短信验证码界面时间倒数出错

### ISSUE THREAD

**Issue by kimmykuang** [PHPStick/beaulys#19]
dev环境链接：http://m.dev.beaulys.com/tmpl/member/member_mobile_bind.html

![image](https://cloud.githubusercontent.com/assets/4559591/16773649/43a28448-488b-11e6-8206-56389738bd16.png)

**Comment by arvingan** [comment]
wap/js/tmpl/member_mobile_bind.js 更新
