### ISSUE TITLE
wap手机注册，图形验证码一直错误

### ISSUE THREAD

**Issue by arvingan** [PHPStick/beaulys#23]
http://m.dev.beaulys.com/tmpl/member/register_mobile_code.html?mobile=18017057704&captcha=cmxk&codekey=ce445e82

**Comment by kimmykuang** [comment]
wap端url: m.dev.beaulys.com请求的接口是dev.beaulys.com/maobile/xxx，验证码也是调用dev子域接口生成的同时会将code写入到cookie但是貌似不用jsonp跨域是无法取到设置的cookie的，最后用jsonp解决；
前端请求设置crossdomain:true，后端返回接口设置请求头：
  header('Access-Control-Allow-Credentials: true');
  header('Access-Control-Allow-Origin: http://m.dev.beaulys.com');
也可以实现。
